name: Node CI

on:
  # Trigger the workflow manually via the GitHub UI
  workflow_dispatch:
  # Trigger the workflow when a pull_request's activity type is opened,
  # synchronize, or reopened.
  pull_request:
  # Trigger the workflow on push
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate:
    strategy:
      matrix:
        version: [14, 16, 18]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - uses: actions/setup-node@16352bb09bc672a073e326c2cc1d3d7d2a3e577e
        with:
          node-version: ${{ matrix.version }}
          cache: "yarn"

      - uses: bahmutov/npm-install@4a274d026feb3c5c4273ac7bbe74c90a7e07cd08
        with:
          install-command:
            yarn --prefer-offline --frozen-lockfile --no-progress --silent
            --ignore-engines

      - run: yarn lint
      - run: yarn test
      - run: yarn test:root
