# inspired by
# - https://github.com/babel/babel/blob/bdb207cb75ae7cde4f2cb03aa2a53eefe6506b18/.github/workflows/release.yml
# - https://github.com/babel/actions/tree/bb571b895aa20aaa3ee4ef58adcde364416acc9a
#
# docs
# - https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
# - https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
name: Release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      version:
        description:
          ⚠️ This workflow can only automatically release versions. Check out
          https://github.com/lerna/lerna/tree/main/commands/version#semver-bump
          for more details.
        required: true
        default: patch

jobs:
  log-updates:
    name: Log packages to publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the new tag
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: This release will publish the following packages
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo ${{ github.event.inputs.version }}
          else
            git diff --name-only HEAD^..HEAD
          fi;

  git-version:
    name: Create git tag and commit when workflow was manually dispatched
    runs-on: ubuntu-latest
    needs: log-updates
    if: github.event_name == 'workflow_dispatch'
    outputs:
      branch: ${{ steps.push.outputs.branch }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set @natterstefan-bot as committer
        run: |
          git config user.name "natterstefan Bot"
          git config user.email "natterstefan-bot@users.noreply.github.com"

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - uses: bahmutov/npm-install@37d870e488074d1a5810ffe9256ebdd81530ab72
        with:
          install-command:
            yarn --prefer-offline --frozen-lockfile --no-progress --silent

      - run:
          HUSKY_SKIP_HOOKS=1 yarn lerna version ${{ github.event.inputs.version
          }} --no-commit-hooks --no-changelog --yes

  npm-release:
    name: Lint, Test and Publish
    runs-on: ubuntu-latest
    needs: git-version
    environment:
      npm
      # The default condition is success(), but this is false when one of the previous jobs is skipped
    if: |
      always() &&
      (needs.git-version.result == 'success' || needs.git-version.result == 'skipped')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - uses: bahmutov/npm-install@37d870e488074d1a5810ffe9256ebdd81530ab72
        with:
          install-command:
            yarn --prefer-offline --frozen-lockfile --no-progress --silent

      - run: yarn lint
      - run: yarn test
      - run: npm run lerna:publish --yes
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  github-release:
    name: Create GitHub release draft
    runs-on: ubuntu-latest
    needs:
      git-version
      # The default condition is success(), but this is false when one of the previous jobs is skipped
    if: |
      always() &&
      (needs.git-version.result == 'success' || needs.git-version.result == 'skipped')
    outputs:
      is-main: ${{ steps.is-main.outputs.result == 1 }}
      changelog: ${{ steps.changelog.outputs.changelog }}
      version: ${{ steps.tags.outputs.new }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if releasing from main
        id: is-main
        uses: babel/actions/ref-matches-branch@v2
        with:
          name: main

      - name: Get tag info
        id: tags
        uses: babel/actions/get-release-tags@v2

      - name: Generate the changelog
        id: changelog
        # alternative: https://github.com/riskledger/generate-changelog/blob/9708d3db7d3bb62ce90bff6352b32e3edbac59c7/main.js
        uses: babel/actions/generate-lerna-changelog@v2
        with:
          from: ${{ steps.tags.outputs.old }}
          to: ${{ steps.tags.outputs.new }}
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a draft GitHub release
        uses: babel/actions/publish-github-release@v2
        with:
          tag: ${{ steps.tags.outputs.new }}
          changelog: ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.BOT_TOKEN }}

  github-push:
    name: Push release commit to "main"
    runs-on: ubuntu-latest
    needs:
      [npm-release, github-release, git-version]
      # The default condition is success(), but this is false when one of the previous jobs is skipped
    if: |
      always() &&
      needs.npm-release.result == 'success' &&
      needs.github-release.result == 'success' &&
      needs.github-release.outputs.is-main
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update CHANGELOG.md
        uses: babel/actions/update-changelog@v2
        with:
          changelog: ${{ needs.github-release.outputs.changelog }}

      - name: Set @natterstefan-bot as committer
        run: |
          git config user.name "natterstefan Bot"
          git config user.email "natterstefan-bot@users.noreply.github.com"

      - name: Commit CHANGELOG.md
        run: |
          git pull
          git add CHANGELOG.md
          git -c user.name="natterstefan Bot" -c user.email="natterstefan-bot@users.noreply.github.com" \
            commit -m "Add ${{ needs.github-release.outputs.version }} to CHANGELOG.md [skip ci]" --no-verify --quiet

      - name: Push to GitHub
        run: |
          git push "https://natterstefan-bot:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main --follow-tags
